source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
target 'StudioGo' do
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'FontAwesome.swift'
  pod 'SwiftyJSON', '~> 4.0'
end
